// Code generated by sqld. DO NOT EDIT.

package db

import "pg"

// DBTX wraps a database connection for query execution.
DBTX :: struct {
	conn: pg.Conn,
}

new_dbtx :: proc(conn: pg.Conn) -> DBTX {
	return DBTX{conn = conn}
}

